resolver: lts-18.14

packages:
- ./qtility-code
- ./qtility
- ./qaws
- ./qaws-sqs
- ./qaws-s3
- ./qtility-brick
- ./mortred
- ./qtility-metrics

allow-different-user: true

extra-deps:
- amazonka-1.6.1@sha256:f58b63e83876f93aa03c54e54b3eb8ba9358af93819d41f4a5a8f8b7d8b8399c,3544
- unliftio-core-0.1.2.0@sha256:b0a7652ffce2284a6cebe05c99eb60573a8fb6631163f34b0b30a80b4a78cb23,1081
- github: codedownio/hs-webdriver
  commit: 96400ea0ba6ef118033d6a727ef4f57c31a187ca
  # nix-sha256: sha256-UNCf218DBAYa2/pBCUBqUAwkry98/1mXGECvq8Sydz4=
- github: Simspace/ekg-prometheus-adapter 
  commit: ea798a02cee0f6aa011eccd730a3d78ecd6491d1
  # nix-sha256: sha256-ramsIKpR9EAcTeCEcL+AsdsFizgKbpZxzREcQrYA0Jk=
- github: Simspace/ekg-wai
  commit: 1fc13cdcb18eecf0f97eadab4f9344beaa3a81de
  # nix-sha256: sha256-dVZ/zDNGECXEY66sb6TidWf57YpX2ytrGFAEeHHIQzo=

