version: '3'

services:
  mortred:
    build: .
    volumes:
      - ..:/workspace:cached
      - ./build/stack-work:/workspace/.stack-work:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

networks:
  default:
    driver: bridge
