name:    mortred
version: "0.0.2"
maintainer: Rickard Andersson <gonz@severnatazvezda.com>
synopsis: Library for setting up and running scrapers with webdriver.
description: A set of setup- and helper-functions for using webdriver in Haskell, with auto-downloads of correct binaries.
license: BSD2
license-file: LICENSE.txt
category: web-scraping, selenium
github: quanterall/mortred
extra-source-files:
- licenses/*

dependencies:

- base >=4.9.1.0 && <5
- webdriver
- rio
- typed-process
- http-client
- http-conduit
- http-types
- http-client-tls
- zip-stream
- conduit
- conduit-extra
- text
- bytestring
- transformers
- errors
- binary-conduit
- stm
- stm-chans
- async
- scalpel
- aeson
- qtility-data
- qtility-th
- lens

default-extensions:
- ApplicativeDo
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DeriveLift
- DerivingStrategies
- DoAndIfThenElse
- DuplicateRecordFields
- EmptyDataDecls
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns
- TypeApplications

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  mortred:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mortred

# Test suite
tests:
  mortred-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - mortred
    - hspec >=2.0.0
